# Generated by Django 4.2.3 on 2023-07-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_check_in_date_booking_check_out_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rooms',
            new_name='room',
        ),
    ]
