# Generated by Django 4.2.3 on 2023-07-10 16:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0004_hostelrooms_price_hostelrooms_hostel_room_no'),
        ('booking', '0004_remove_booking_user_booking_booking_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(help_text='Enter valid email', max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='hostel_main.hostelrooms'),
        ),
    ]
