# Generated by Django 4.2.3 on 2023-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0009_remove_hostelrooms_book'),
        ('booking', '0007_remove_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(related_name='booking', to='hostel_main.hostelrooms'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(help_text='Format: yy/mm/dd'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(help_text='Format: yy/mm/dd'),
        ),
    ]
