# Generated by Django 4.2.3 on 2023-07-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0011_rename_amenities_hostelrooms_description_and_more'),
        ('booking', '0008_booking_room_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(related_name='booked', to='hostel_main.hostelrooms'),
        ),
    ]
