# Generated by Django 4.2.3 on 2023-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0012_remove_booking_room_booking_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateField(
                help_text="Format: yy-mm-dd", verbose_name="check in date"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(
                help_text="Format: yy-mm-dd", verbose_name="check out date"
            ),
        ),
    ]
