# Generated by Django 4.2.2 on 2023-06-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter hostel name', max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HostelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos%y%m%d')),
                ('is_occupied', models.BooleanField(default=False)),
                ('room_capacity', models.IntegerField(default=2)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel_main.hostel')),
            ],
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['-created'], name='hostel_main_created_74891d_idx'),
        ),
    ]
