# Generated by Django 4.2.3 on 2023-07-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, upload_to='static_root%hostel_img%y%m%d'),
        ),
        migrations.AlterField(
            model_name='hostelrooms',
            name='image',
            field=models.ImageField(blank=True, upload_to='static_root%room_img%y%m%d'),
        ),
    ]
