# Generated by Django 4.2.3 on 2023-07-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0002_hostel_image_alter_hostelrooms_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hostel_img/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hostelrooms',
            name='image',
            field=models.ImageField(blank=True, upload_to='room_img/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='hostelrooms',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
