# Generated by Django 4.2.3 on 2023-07-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0003_alter_hostel_image_alter_hostelrooms_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelrooms',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='hostelrooms',
            constraint=models.UniqueConstraint(fields=('hostel', 'room_number'), name='hostel_room_no'),
        ),
    ]
