# Generated by Django 4.2.3 on 2023-07-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0004_hostelrooms_price_hostelrooms_hostel_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='user',
        ),
    ]
