# Generated by Django 4.2.3 on 2023-07-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_room_booking_user'),
        ('hostel_main', '0005_remove_hostel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelrooms',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_room', to='booking.booking'),
        ),
    ]
