# Generated by Django 4.2.3 on 2023-07-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_room_booking_user'),
        ('hostel_main', '0006_hostelrooms_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelrooms',
            name='book',
        ),
        migrations.AddField(
            model_name='hostelrooms',
            name='book',
            field=models.ManyToManyField(related_name='booked_room', to='booking.booking'),
        ),
    ]
