# Generated by Django 4.2.3 on 2023-07-11 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostel_main', '0007_remove_hostelrooms_book_hostelrooms_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel', to=settings.AUTH_USER_MODEL),
        ),
    ]
