# Generated by Django 4.2.3 on 2023-07-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0008_hostel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostelrooms',
            name='book',
        ),
    ]
