# Generated by Django 4.2.3 on 2023-07-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0009_remove_hostelrooms_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='slogan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hostelrooms',
            name='amenities',
            field=models.TextField(blank=True),
        ),
    ]
