# Generated by Django 4.2.3 on 2023-07-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_main', '0011_rename_amenities_hostelrooms_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelrooms',
            old_name='price',
            new_name='bed_price',
        ),
        migrations.AddField(
            model_name='hostelrooms',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
