# Generated by Django 4.2.2 on 2023-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Admin account?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-email'],
                'indexes': [models.Index(fields=['is_active'], name='account_use_is_acti_428f36_idx')],
            },
        ),
    ]
