# Generated by Django 4.2.2 on 2023-06-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_admin',
            field=models.CharField(default='', max_length=10),
        ),
    ]
