# Generated by Django 4.2.3 on 2023-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeuser_id_alter_customeuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
