# Generated by Django 4.2.2 on 2023-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeuser_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
