# Generated by Django 4.2.2 on 2023-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeuser_options_alter_customeuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='confirm_password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
