# Generated by Django 4.2.3 on 2023-07-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_user_booking_booking_option_and_more'),
        ('accounts', '0003_alter_customeuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.booking'),
        ),
    ]
