# Generated by Django 4.2.3 on 2023-07-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeuser_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='booking',
        ),
    ]
